### PR TITLE
FORGE-2418: Upgrade Hibernate Validator to version 5.2.0.Final

### PR DESCRIPTION
**Pull request by oscerd**
Hi,

This PR is related to:
https://issues.jboss.org/browse/FORGE-2418

Bye,
Andrea

### CODE REVIEW

**Comment by gastaldi** [comment]
Why was this PR closed? It looks good to me

**Comment by oscerd** [comment]
Reopened. I've closed the PR due the CI errors reported above.

**Comment by gastaldi** [comment]
We'll fix these CI errors when moving to a new CI server. Have you run the tests locally?

**Comment by oscerd** [comment]
Yes. Locally everything seems fine. The next time I will not consider the
CI results and just run the tests locally :-)
Il 01/ago/2015 23:12, "George Gastaldi" <notifications@github.com> ha
scritto:

**Comment by gastaldi** [comment]
It looks like 5.2.1.Final is out: http://in.relation.to/2015/07/30/hibernate-validator-521-final/

**Comment by oscerd** [comment]
You're right.. I'll submit a new PR today :-)
Il 02/ago/2015 09:05, "George Gastaldi" <notifications@github.com> ha
scritto:

**Pull request closed without merging**
