### PR TITLE
FORGE-1975: Upgrade aesh version to 0.61

### PR DESCRIPTION
**Pull request by jerr**
Update to version 0.59 to have the multi-input option parsing and more, see the aesh changelog.

### CODE REVIEW

**Comment by jerr** [comment]
George, I disable the check the status, because I have a problem in the initialization phase. Can you tell me what you think?
https://github.com/forge/core/pull/565/files#diff-6cec1e54ec5d3b96613732f985a73905R169

**Comment by gastaldi** [comment]
I think that's fine. What problem are you facing?


Enviado do meu smartphone Samsung Galaxy.<div>
</div><div>
</div><div>-------- Mensagem original --------</div><div>De: Jérémie Lagarde <notifications@github.com> </div><div>Data: 16/05/2015  23:17  (GMT-03:00) </div><div>Para: forge/core <core@noreply.github.com> </div><div>Assunto: Re: [core] Upgrade aesh version to 0.59 (#565) </div><div>
</div>George, I disable the check the status, because I have a problem in the initialization phase. Can you tell me what you think?
https://github.com/forge/core/pull/565/files#diff-6cec1e54ec5d3b96613732f985a73905R169

---

**Comment by jerr** [comment]
Look at line 169 (see the link) , I had to disable the status check because we request a list of commands during the initialisaion phase.
https://github.com/forge/core/pull/565/files#diff-6cec1e54ec5d3b96613732f985a73905R169

There probably has a better way to do this.

**Comment by jerr** [comment]
To correct text addon tests , delete the file .lastupdate in the local repository for furnace-bom-2.18.0.Final.pom

**Comment by gastaldi** [comment]
For some reason, Ctrl+D doesn't seem to work as before in your PR. It was supposed to quit Forge, but it seems to hang for some reason

**Comment by gastaldi** [comment]
Also, make sure to rebase this commit with the JIRA issue ID for tracking purposes

**Comment by jerr** [comment]
gastaldi : now you can use CTRL+D

**Comment by gastaldi** [comment]
I see some failures while running FacesScaffoldTest:

Failed tests: 
  FacesScaffoldTest.testScaffoldSetup:76 
Expected: is an instance of org.jboss.forge.addon.ui.result.CompositeResult
     but: <Success [Field firstName created]> is a org.jboss.forge.addon.ui.result.Results$SuccessfulResult
Tests in error: 
  FacesScaffoldTest.shouldCreateOneErrorPageForEachErrorCode:82 » TimeoutException_$$_javassist_1dadbe69-7808-4ee2-9fff-dc594fdad2d6


This may indicate that the shell-test-harness is not waiting long enough for a feedback.

**Comment by jerr** [comment]
I do not reproduce it on my machine but I will control the shell ending in the tests. I'll have more time for that this weekend.

**Comment by jerr** [comment]
Thread leaks and potential deadlocks are fixed in eash. Waiting new released version of it.

**Comment by jerr** [comment]
Waiting aesh 0.61 to remove deadlock for tests

**Comment by jerr** [comment]
To correct text addon tests , delete the file .lastupdate in the local repository for furnace-bom-2.18.2.Final.pom

**Comment by jerr** [comment]
Can you increase the max build time to validate this pull request? Thank you.

Regards
Jérémie.

**Comment by gastaldi** [comment]
Merged in https://github.com/forge/core/commit/8dbc065fa, thanks!

**Pull request closed without merging**
